FROM n8nio/n8n:latest

# إعداد المتغيرات البيئية الافتراضية
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=rayen
ENV N8N_BASIC_AUTH_PASSWORD=rzougabenq2021
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
